
#name: Jekyll site CI 

#on:
 # push:
  #  branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

#jobs:
 # build:

  #  runs-on: ubuntu-latest

   # steps:
     # - name: Checkout code
    #    uses: actions/checkout@v3
    
      #- name: SonarCloud scan
       # uses: sonarsource/sonarqube-scan-action@master
        #env:
         #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           #  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

on:
  #Análise de gatilho ao enviar solicitações mestre ou pull e ao criar uma solicitação de pull

  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      variables:
       
        SONAR_SCANNER_VERSION: 4.4.0.2170
        SONAR_SCANNER_HOME: $HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        SONAR_SCANNER_OPTS: -server

        phases:
        install:
        commands:
            - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
            - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        build:
         commands:
         - $HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin/sonar-scanner -Dsonar.organization=randall-reilly-eda -Dsonar.projectKey=$SONAR_SCANNER_PROJECT_KEY -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.scm.enabled=false -Dsonar.login=$SONAR_TOKEN